---
title: "PLS - Hoteles"
author: "Roberto Gil-Saura"
date: "2/4/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-width: 100%;
  margin-left: 10px;
  margin-right: 10px;}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressMessages(library(dplyr))
suppressMessages(library(readxl))
suppressMessages(library(seminr))
suppressMessages(library(expss))
suppressMessages(data.h <- read_excel("~/R/r-data/00.wp001/hoteles.xls"))
suppressMessages(data.a <- read_spss("~/R/r-data/00.wp001/agencias.sav"))
options(width=9999)
```

# modelos PLS {.tabset .tabset-pills}

## Hoteles

```{r load,warning=FALSE, message=FALSE, fig.width=16, fig.height=9}
df.h <-select(data.h,
              ID=CUESTIONARIO,
               TRUST1=P6,
               TRUST2=P7,
               TRUST3=P8,
               COMMITMENT1=P9,
               COMMITMENT2=P10,
               COMMITMENT3=P11,
               COMMITMENT4=P12,
               VcC1=P13,
               VcC2=P14,
               VcC3=P15,
               VcC4=P16,
               VcC5=P17,
               VcC6=P18,
               ECOSAT1=P23,
               ECOSAT2=P24,
               ECOSAT3=P25,
               SOCSAT1=P26,
               SOCSAT2=P27,
               SOCSAT3=P28,
               ICT1=P97,
               ICT2=P98,
               ICT3=P99,
               ICT4=P100
              )
simple_mm <- constructs(
     composite("ICT", multi_items("ICT", 1:4)),
     composite("VcC", multi_items("VcC", 1:6)),
     composite("TRUST", multi_items("TRUST", 1:3)),
     composite("COMMITMENT", multi_items("COMMITMENT", 1:4)),
     composite("ECOSAT", multi_items("ECOSAT", 1:3)),
     composite("SOCSAT", multi_items("SOCSAT",1:3))
     )

# Create structural model ----
simple_sm <- relationships(
     paths(from = c("ICT"), to = c("VcC")),
     paths(from = c("VcC"), to = c("TRUST","COMMITMENT")),
     paths(from = c("TRUST"), to = c("COMMITMENT", "SOCSAT")),
     paths(from = c("COMMITMENT"), to = c("SOCSAT")),
     paths(from = c("SOCSAT"), to = c("ECOSAT"))
     )



# Estimate the model
simple_model <- estimate_pls(data = df.h,
                                      measurement_model = simple_mm,
                                      structural_model  = simple_sm,
                                      inner_weights = path_weighting,
                                      missing = mean_replacement,
                                      missing_value = NA)
```

Resumen del modelo

```{r }
# Summarize the model results
summary_simple <- summary(simple_model)
```

```{r}
# Inspect the structural paths
summary_simple$paths
```

```{r}
# Inspect the construct reliability metrics
summary_simple$reliability
```


```{r warning=FALSE, message=FALSE, fig.width=16, fig.height=9}
# Plot model
plot(simple_model, theme=seminr_theme_smart())
```



```{r}
# Bootstrap the model
boot_simple <- bootstrap_model(seminr_model = simple_model,
                                        nboot = 1000,
                                        cores = NULL,
                                        seed = 123)

```



```{r}
# Store the summary of the bootstrapped model
sum_boot_simple <- summary(boot_simple)
```



```{r}
# Inspect the bootstrapped structural paths
sum_boot_simple$bootstrapped_paths
```



```{r}
# Inspect the bootstrapped outer weights
sum_boot_simple$bootstrapped_weights
# Write the bootstrapped paths object to csv file
write.csv(x = sum_boot_simple$bootstrapped_weights, file = "boot_paths.csv")
```


```{r warning=FALSE, message=FALSE, fig.width=16, fig.height=9}
# Generate the plot for exporting
plot(summary_simple$reliability)
plot(boot_simple, theme=seminr_theme_smart())
```

## Agencias

```{r warning=FALSE, message=FALSE, fig.width=16, fig.height=9}
df.a <-select(data.a,
              ID=CUESTIONARIO,
               TRUST1=P8,
               TRUST2=P9,
               TRUST3=P10,
               COMMITMENT1=P11,
               COMMITMENT2=P12,
               COMMITMENT3=P13,
               COMMITMENT4=P14,
               VcC1=P15,
               VcC2=P16,
               VcC3=P17,
               VcC4=P18,
               VcC5=P19,
               VcC6=P20,
               ECOSAT1=P43,
               ECOSAT2=P44,
               ECOSAT3=P45,
               SOCSAT1=P46,
               SOCSAT2=P47,
               SOCSAT3=P48,
               ICT1=P110,
               ICT2=P111,
               ICT3=P112,
               ICT4=P113,
               ICT5=P114
              )
simple_mm <- constructs(
     composite("ICT", multi_items("ICT", 1:5)),
     composite("VcC", multi_items("VcC", 1:6)),
     composite("TRUST", multi_items("TRUST", 1:3)),
     composite("COMMITMENT", multi_items("COMMITMENT", 1:4)),
     composite("ECOSAT", multi_items("ECOSAT", 1:3)),
     composite("SOCSAT", multi_items("SOCSAT",1:3))
     )

# Create structural model ----
simple_sm <- relationships(
     paths(from = c("ICT"), to = c("VcC")),
     paths(from = c("VcC"), to = c("TRUST","COMMITMENT")),
     paths(from = c("TRUST"), to = c("COMMITMENT", "SOCSAT")),
     paths(from = c("COMMITMENT"), to = c("SOCSAT")),
     paths(from = c("SOCSAT"), to = c("ECOSAT"))
     )



# Estimate the model
simple_model <- estimate_pls(data = df.a,
                                      measurement_model = simple_mm,
                                      structural_model  = simple_sm,
                                      inner_weights = path_weighting,
                                      missing = mean_replacement,
                                      missing_value = NA)
```

Resumen del modelo

```{r }
# Summarize the model results
summary_simple <- summary(simple_model)
```

```{r}
# Inspect the structural paths
summary_simple$paths
```

```{r}
# Inspect the construct reliability metrics
summary_simple$reliability
```


```{r warning=FALSE, message=FALSE, fig.width=16, fig.height=9}
# Plot model
plot(simple_model, theme=seminr_theme_smart())
```



```{r}
# Bootstrap the model
boot_simple <- bootstrap_model(seminr_model = simple_model,
                                        nboot = 1000,
                                        cores = NULL,
                                        seed = 123)

```



```{r}
# Store the summary of the bootstrapped model
sum_boot_simple <- summary(boot_simple)
```



```{r}
# Inspect the bootstrapped structural paths
sum_boot_simple$bootstrapped_paths
```



```{r}
# Inspect the bootstrapped outer weights
sum_boot_simple$bootstrapped_weights
# Write the bootstrapped paths object to csv file
write.csv(x = sum_boot_simple$bootstrapped_weights, file = "boot_paths.csv")
```


```{r warning=FALSE, message=FALSE, fig.width=16, fig.height=9}
# Generate the plot for exporting
plot(summary_simple$reliability)
plot(boot_simple, theme=seminr_theme_smart())
```